### ISSUE TITLE
[TELEFONICA-001] Configuración inicial del cliente Telefónica del Perú

### ISSUE THREAD

**Issue by reyer3** [reyer3/Pulso-AI#12]
## 🎯 Objetivo
Establecer la configuración base para Telefónica del Perú como cliente de arranque del sistema Pulso-AI.

## 📋 Contexto de Negocio
- **Cliente**: Telefónica del Perú (Movistar)
- **Fuente de datos**: BigQuery (mibot-222814.BI_USA.dash_P3fV4dWNeMkN5RJMhV8e_vw_operativo)
- **Objetivo**: Dashboard de productividad para área de cobranza
- **SLA**: Dashboard funcionando en <4 horas desde configuración

### Configuración del Cliente
- [ ] Crear estructura de directorio `clients/telefonica-peru/`
- [ ] Archivo `config.yaml` con dimensiones específicas de Telefónica
- [ ] Mapeo de campos BigQuery a modelo dominio estándar
- [ ] Validación de configuración automática

### Dimensiones Requeridas
```yaml
dimensions:
  ejecutivo: {source_field: "ejecutivo", type: "categorical"}
  servicio: {source_field: "linea_servicio", valid_values: ["MOVIL", "FIJA"]}
  cartera: {source_field: "tipo_cartera", valid_values: ["Gestión Temprana", "Altas Nuevas"]}
  zona: {source_field: "zona_geografica", type: "categorical"}
  mes: {source_field: "fecha_gestion", type: "temporal", format: "YYYY-MM"}
```

### Métricas Requeridas
```yaml
metrics:
  pdps_por_hora: {formula: "pdp_count / horas_trabajadas", format: "decimal_2"}
  tasa_contactabilidad: {formula: "(contactos / total_gestiones) * 100", format: "percentage"}
  compromisos_cumplidos: {formula: "(compromisos_cumplidos / compromisos_total) * 100", format: "percentage"}
  productividad_diaria: {formula: "gestiones_realizadas / dias_trabajados", format: "decimal_1"}
```

### Estructura de Archivos
```
clients/telefonica-peru/
├── config.yaml                 # Configuración principal
├── data_mapping.yaml          # Mapeo de campos BigQuery
├── homologation_rules.yaml    # Reglas de homologación
├── dashboard_template.yaml    # Template del dashboard
└── README.md                  # Documentación específica
```

### Validaciones
- [ ] Schema validation para configuración
- [ ] Test de conectividad a BigQuery
- [ ] Validación de campos obligatorios
- [ ] Test de queries con datos reales

## 📊 Definición de Terminado
- [ ] Configuración deployada y validada
- [ ] Tests de integración pasando
- [ ] Documentación actualizada
- [ ] Script de setup ejecutándose correctamente

## 🔗 Dependencias
- Base hexagonal architecture (#TBD)
- BigQuery adapter (#TBD)
- Configuration validation system (#TBD)

## 📅 Timeline
**Estimación**: 4-6 horas  
**Prioridad**: P0 (Blocker para otros issues)

## 🏷️ Labels
`client-telefonica`, `phase-1-mvp`, `configuration`, `p0-blocker`
