### ISSUE TITLE
[TELEFONICA-003] Implementar ETL Pipeline dimensional para Telefónica del Perú

### ISSUE THREAD

**Issue by reyer3** [reyer3/Pulso-AI#14]
## 🎯 Objetivo
Implementar el pipeline ETL específico para Telefónica del Perú basado en el schema dimensional ya documentado, siguiendo el enfoque lean y arquitectura separada.

## 📋 Contexto Técnico
Basado en la documentación existente del proyecto:
- **Schema Dimensional**: Ya definido en `ANALISIS TELEFONICA PERU - SCHEMA DIMENSIONAL`
- **Enfoque**: Lean incremental con componentes reutilizables
- **Arquitectura**: ETL separado del API (BigQuery → PostgreSQL → API)

### **1. ConfigurableExtractor (Reutilizable)**
```python
# shared/etl/components/extractor.py
class ConfigurableExtractor:
    """Extractor que se adapta a cualquier fuente via config."""
    
    def __init__(self, source_config: SourceConfig):
        self._config = source_config
        self._adapter = self._create_adapter()
    
    async def extract_incremental(self, fecha_proceso: date) -> polars.DataFrame:
        """Método uniforme independiente de la fuente."""
        base_query = self._config.queries.incremental_template
        query = self._replace_template_vars(base_query, {
            'fecha_proceso': fecha_proceso,
            'table_name': self._config.table_name,
            'partition_field': self._config.partition_field
        })
        return await self._adapter.execute_query(query)
```

### **2. DimensionalTransformer (Reutilizable)**
```python
# shared/etl/components/transformer.py
class DimensionalTransformer:
    """Transformer que construye hechos y dimensiones via config."""
    
    def __init__(self, schema_config: SchemaConfig):
        self._config = schema_config
    
    def build_dimensions(self, raw_data: pl.DataFrame) -> Dict[str, pl.DataFrame]:
        """Construye todas las dimensiones según config."""
        return {
            'dim_tiempo': self._build_dim_tiempo(),
            'dim_cliente': self._build_dim_cliente(raw_data),
            'dim_servicio': self._build_dim_servicio(),
            'dim_cartera': self._build_dim_cartera(),
            'dim_canal': self._build_dim_canal(),
            'dim_campana': self._build_dim_campana(raw_data)
        }
    
    def build_facts(self, raw_data: pl.DataFrame) -> Dict[str, pl.DataFrame]:
        """Construye todas las tablas de hechos según config."""
        return {
            'fact_asignacion': self._build_fact_asignacion(raw_data),
            'fact_deuda_apertura': self._build_fact_deuda_apertura(raw_data),
            'fact_gestiones': self._build_fact_gestiones(raw_data),
            'fact_gestiones_expandida': self._build_fact_gestiones_expandida(raw_data),
            'fact_pagos_atribuidos': self._build_fact_pagos_atribuidos(raw_data)
        }
```

### **Schema Dimensional Completo**
- [ ] **DIM_TIEMPO**: Una fila por fecha con campos año, mes, día, día_semana
- [ ] **DIM_CLIENTE**: cod_luna (PK), cliente, dni - DISTINCT y validado
- [ ] **DIM_SERVICIO**: 'MOVIL'/'FIJA' con cod_sistema_pagos
- [ ] **DIM_CARTERA**: 'Temprana', 'AN', 'CF', 'Regular' con limpieza REGEXP
- [ ] **DIM_CANAL**: 'CALL'/'VOICEBOT' con flag es_automatico
- [ ] **DIM_CAMPAÑA**: servicio + cartera + mes + vct específico

### **Tablas de Hechos Específicas**
```sql
-- FACT_ASIGNACION
GRANO: cod_luna + fecha_asignacion + id_campaña
CARDINALIDAD: ~300K-500K filas
MÉTRICA: clientes_asignados (INT = 1)

-- FACT_DEUDA_APERTURA  
GRANO: cuenta + fecha_apertura_campaña + nro_documento
CARDINALIDAD: ~1M-2M filas
MÉTRICAS: monto_exigible_apertura, documentos_deuda

-- FACT_GESTIONES
GRANO: fecha_gestion + hora_gestion + ejecutivo + canal  
CARDINALIDAD: ~500K-1M filas
MÉTRICAS: total_gestiones, contactos_efectivos, no_contactos, gestiones_pdp

-- FACT_GESTIONES_EXPANDIDA
GRANO: fecha_gestion + hora_gestion + ejecutivo + canal + cod_luna
PROPÓSITO: Análisis detallado por cliente y secuencias multi-canal

-- FACT_PAGOS_ATRIBUIDOS
GRANO: nro_documento + fecha_pago
LÓGICA: Última gestión <= fecha_pago en ventana de 30 días
```

### **Performance y Calidad**
- [ ] ETL proceso completo: <30 minutos
- [ ] Validaciones de integridad referencial
- [ ] Logs detallados por cada step
- [ ] Rollback automático en caso de error

### **ETL Config**
```yaml
# clients/telefonica-peru/etl-config.yaml
source:
  type: "bigquery"
  bigquery:
    project_id: "mibot-222814"
    dataset: "BI_USA"
    credentials_path: "/secrets/telefonica-bq-key.json"
  
  table_name: "dash_P3fV4dWNeMkN5RJMhV8e_vw_operativo"
  partition_field: "_PARTITIONTIME"
  
  queries:
    incremental_template: |
      SELECT 
        fecha_gestion,
        hora_gestion,
        ejecutivo,
        canal,
        contactabilidad,
        es_pdp,
        cod_luna,
        tipo_cartera,
        linea_servicio,
        monto_exigible,
        nro_documento
      FROM `{{project_id}}.{{dataset}}.{{table_name}}`
      WHERE _PARTITIONTIME = '{{fecha_proceso}}'

target:
  type: "postgresql"
  postgresql:
    host: "telefonica-datamart.postgres"
    database: "telefonica_datamart"
    schema: "dwh"
    credentials: "/secrets/telefonica-pg-creds"
```

### **Schema Config**
```yaml  
# clients/telefonica-peru/schema-config.yaml
dimensions:
  cliente:
    source_fields: ["cod_luna", "cliente", "dni"]
    primary_key: "cod_luna"
    validations:
      - "dni IS NOT NULL"
      - "DISTINCT cod_luna"
    
  cartera:
    source_field: "tipo_cartera"
    valid_values: ["Gestión Temprana", "Altas Nuevas", "CF", "Regular"]
    extraction_rule: "REGEXP_EXTRACT(archivo, r'(Temprana|AN|CF|Regular)')"

facts:
  gestiones:
    grain: ["fecha_gestion", "hora_gestion", "ejecutivo", "canal"]
    metrics:
      total_gestiones: "COUNT(*)"
      contactos_efectivos: "SUM(CASE WHEN contactabilidad = 'CONTACTO EFECTIVO' THEN 1 ELSE 0 END)"
      gestiones_pdp: "SUM(CASE WHEN es_pdp = true THEN 1 ELSE 0 END)"
    aggregations:
      cod_lunas_gestionados: "ARRAY_AGG(DISTINCT cod_luna)"
```

### **Data Quality Checks**
```sql
-- Validar trazabilidad pagos → deuda
SELECT COUNT(*) as missing_payments
FROM fact_pagos_atribuidos p
LEFT JOIN fact_deuda_apertura d ON p.nro_documento = d.nro_documento
WHERE d.nro_documento IS NULL;

-- Verificar atribución de pagos
SELECT 
  metodo_atribucion,
  COUNT(*) as cantidad,
  SUM(monto_pagado) as monto_total
FROM fact_pagos_atribuidos
GROUP BY metodo_atribucion;

-- Verificar cardinalidad gestiones
SELECT canal, ejecutivo, COUNT(*) as registros
FROM fact_gestiones
GROUP BY canal, ejecutivo
HAVING COUNT(*) > 1000
ORDER BY registros DESC;
```

### **Business Logic Tests**
- [ ] Test atribución: última gestión <= fecha_pago en ventana 30 días
- [ ] Test multi-canal: secuencias VOICEBOT → CALL
- [ ] Test homologación: mapeo ejecutivo 'DISCADOR'/'VOICEBOT'
- [ ] Test dimensiones: valores válidos en carteras y servicios

## 📁 Estructura de Archivos
```
shared/etl/
├── components/
│   ├── extractor.py              # ConfigurableExtractor
│   ├── transformer.py           # DimensionalTransformer  
│   ├── loader.py                # PostgreSQLLoader
│   └── validator.py             # DataQualityValidator
├── orchestrator.py              # ETLOrchestrator
└── config_loader.py             # ConfigLoader

clients/telefonica-peru/
├── etl-config.yaml              # Configuración fuente BigQuery
├── schema-config.yaml           # Configuración schema dimensional
└── pipeline-schedule.yaml       # Configuración schedule
```

## 🔗 Dependencias
- ConfigurableExtractor components (#TBD)
- PostgreSQL datamart setup (#TBD)  
- Dimensional schema creation (#TBD)
- Telefónica BigQuery credentials (#TBD)

## 📅 Timeline
**Estimación**: 12-16 horas  
**Prioridad**: P0 (Crítico para arquitectura separada)

## 🏷️ Labels
`client-telefonica`, `etl-pipeline`, `dimensional-schema`, `lean-architecture`, `p0-blocker`
