### ISSUE TITLE
[TELEFONICA-004] Implementar API GraphQL dinámico conectado a PostgreSQL datamart

### ISSUE THREAD

**Issue by reyer3** [reyer3/Pulso-AI#15]
## 🎯 Objetivo
Implementar el API GraphQL dinámico para Telefónica del Perú, conectando al datamart PostgreSQL y siguiendo el enfoque de arquitectura separada lean.

## 📋 Contexto Técnico
Basado en la documentación del proyecto:
- **Fuente de datos**: PostgreSQL datamart (dimensional schema ya definido)
- **Tecnología**: FastAPI + Strawberry GraphQL
- **Enfoque**: Schema dinámico generado desde configuración
- **Arquitectura**: API separado del ETL, consultas optimizadas

### **1. PostgreSQLRepository (Adaptador)**
```python
# core-template/src/infrastructure/adapters/postgresql/telefonica_repository.py
class TelefonicaPostgreSQLRepository(IClientDataRepository):
    """Repository que conecta al datamart dimensional PostgreSQL."""
    
    def __init__(self, config: PostgreSQLConfig):
        self.pool = asyncpg.create_pool(
            host=config.host,
            database=config.database,
            user=config.user,
            password=config.password,
            min_size=5,
            max_size=20
        )
        self.schema = config.schema  # "dwh"
    
    async def get_gestiones_by_filters(
        self, 
        filters: Dict[str, Any]
    ) -> pl.DataFrame:
        """Query optimizada al modelo dimensional."""
        
        # Query base usando el schema dimensional
        base_query = """
        SELECT 
            dt.fecha,
            dc.ejecutivo,
            ds.servicio,
            dcar.tipo_cartera,
            fg.total_gestiones,
            fg.contactos_efectivos,
            fg.gestiones_pdp,
            ROUND(fg.contactos_efectivos::float / fg.total_gestiones * 100, 2) as tasa_contactabilidad
        FROM {schema}.fact_gestiones fg
        JOIN {schema}.dim_tiempo dt ON fg.fecha_id = dt.fecha_id
        JOIN {schema}.dim_canal dc ON fg.canal_id = dc.canal_id  
        JOIN {schema}.dim_servicio ds ON fg.servicio_id = ds.servicio_id
        JOIN {schema}.dim_cartera dcar ON fg.cartera_id = dcar.cartera_id
        WHERE {where_conditions}
        """
        
        query = self._build_filtered_query(base_query, filters)
        
        async with self.pool.acquire() as conn:
            result = await conn.fetch(query)
            return pl.DataFrame([dict(row) for row in result])
    
    async def get_available_dimensions(
        self, 
        dimension: str, 
        applied_filters: Dict[str, Any] = None
    ) -> List[str]:
        """Optimización para cross-filtering usando índices dimensionales."""
        
        dimension_queries = {
            "ejecutivo": """
                SELECT DISTINCT ejecutivo 
                FROM {schema}.fact_gestiones fg
                JOIN {schema}.dim_canal dc ON fg.canal_id = dc.canal_id
                WHERE dc.ejecutivo IS NOT NULL AND {filters}
                ORDER BY ejecutivo
            """,
            "servicio": """
                SELECT DISTINCT servicio
                FROM {schema}.dim_servicio ds
                JOIN {schema}.fact_gestiones fg ON ds.servicio_id = fg.servicio_id
                WHERE {filters}
            """,
            "cartera": """
                SELECT DISTINCT tipo_cartera
                FROM {schema}.dim_cartera dcar
                JOIN {schema}.fact_gestiones fg ON dcar.cartera_id = fg.cartera_id
                WHERE {filters}
            """
        }
        
        query = dimension_queries.get(dimension)
        if not query:
            return []
            
        filtered_query = self._apply_cross_filters(query, applied_filters)
        
        async with self.pool.acquire() as conn:
            result = await conn.fetch(filtered_query)
            return [row[0] for row in result]
```

### **2. GraphQLSchemaGenerator (Reutilizable)**
```python
# shared/graphql/schema_generator.py
class GraphQLSchemaGenerator:
    """Genera schema GraphQL dinámico basado en configuración del cliente."""
    
    def __init__(self, client_config: ClientConfig):
        self._config = client_config
        self._repository = self._create_repository()
    
    def generate_schema(self) -> strawberry.Schema:
        """Genera schema completo basado en dimensiones y métricas del cliente."""
        
        # Tipos dinámicos basados en configuración
        GestionData = self._create_gestion_type()
        FilterInput = self._create_filter_input_type()
        DimensionValues = self._create_dimension_values_type()
        
        @strawberry.type
        class Query:
            @strawberry.field
            async def gestiones(
                self, 
                filters: Optional[FilterInput] = None
            ) -> List[GestionData]:
                filter_dict = filters.__dict__ if filters else {}
                df = await self._repository.get_gestiones_by_filters(filter_dict)
                return [GestionData(**row) for row in df.to_dicts()]
            
            @strawberry.field
            async def available_values(
                self,
                dimension: str,
                applied_filters: Optional[FilterInput] = None
            ) -> DimensionValues:
                filter_dict = applied_filters.__dict__ if applied_filters else {}
                values = await self._repository.get_available_dimensions(
                    dimension, 
                    filter_dict
                )
                return DimensionValues(dimension=dimension, values=values)
        
        return strawberry.Schema(query=Query)
    
    def _create_gestion_type(self):
        """Crea tipo GestionData dinámico basado en métricas configuradas."""
        
        # Campos base siempre presentes
        fields = {
            'fecha': datetime,
            'ejecutivo': Optional[str],
            'servicio': str,
            'cartera': str
        }
        
        # Agregar métricas según configuración
        for metric_name, metric_config in self._config.metrics.items():
            if metric_config.format == "percentage":
                fields[metric_name] = Optional[float]
            elif metric_config.format == "decimal":
                fields[metric_name] = Optional[float]
            else:
                fields[metric_name] = Optional[int]
        
        return strawberry.type(
            type("GestionData", (), fields)
        )
```

### **API Performance**
- [ ] Query base gestiones: <200ms para 10K registros
- [ ] Cross-filtering suggestions: <100ms
- [ ] Conexión pool: 5-20 conexiones concurrentes
- [ ] Cache Redis para queries frecuentes: TTL 5 minutos

### **Schema Dinámico Funcional**
```graphql
# Schema generado automáticamente para Telefónica
type Query {
  gestiones(filters: TelefonicaFilters): [TelefonicaGestion!]!
  availableValues(dimension: String!, appliedFilters: TelefonicaFilters): DimensionValues!
  metricsAggregate(filters: TelefonicaFilters): TelefonicaMetrics!
}

type TelefonicaGestion {
  fecha: DateTime!
  ejecutivo: String
  servicio: String!
  cartera: String!
  tasa_contactabilidad: Float
  pdps_por_hora: Float
  total_gestiones: Int!
  contactos_efectivos: Int!
}

input TelefonicaFilters {
  fechaInicio: DateTime
  fechaFin: DateTime
  ejecutivos: [String!]
  servicios: [String!]
  carteras: [String!]
}

type DimensionValues {
  dimension: String!
  values: [String!]!
  counts: [DimensionCount!]!
}
```

### **Queries Específicas Optimizadas**
```sql
-- Query gestiones con filtros múltiples (optimizada para índices)
SELECT 
    dt.fecha,
    dc.ejecutivo,
    ds.servicio,
    dcar.tipo_cartera,
    fg.total_gestiones,
    fg.contactos_efectivos,
    fg.gestiones_pdp,
    ROUND(fg.contactos_efectivos::float / fg.total_gestiones * 100, 2) as tasa_contactabilidad,
    ROUND(fg.gestiones_pdp::float / fge.horas_trabajadas, 2) as pdps_por_hora
FROM dwh.fact_gestiones fg
JOIN dwh.dim_tiempo dt ON fg.fecha_id = dt.fecha_id
JOIN dwh.dim_canal dc ON fg.canal_id = dc.canal_id  
JOIN dwh.dim_servicio ds ON fg.servicio_id = ds.servicio_id
JOIN dwh.dim_cartera dcar ON fg.cartera_id = dcar.cartera_id
LEFT JOIN dwh.fact_gestiones_expandida fge ON fg.gestion_id = fge.gestion_id
WHERE dt.fecha BETWEEN $1 AND $2
  AND ($3::text[] IS NULL OR dc.ejecutivo = ANY($3))
  AND ($4::text[] IS NULL OR ds.servicio = ANY($4))
  AND ($5::text[] IS NULL OR dcar.tipo_cartera = ANY($5))
ORDER BY dt.fecha DESC, fg.total_gestiones DESC;

-- Query cross-filtering optimizada
WITH filtered_gestiones AS (
    SELECT DISTINCT fg.ejecutivo_id, fg.servicio_id, fg.cartera_id
    FROM dwh.fact_gestiones fg
    JOIN dwh.dim_tiempo dt ON fg.fecha_id = dt.fecha_id
    WHERE dt.fecha BETWEEN $1 AND $2
      AND ($2::int[] IS NULL OR fg.servicio_id = ANY($2))
)
SELECT DISTINCT dc.ejecutivo
FROM dwh.dim_canal dc
JOIN filtered_gestiones fg ON dc.canal_id = fg.ejecutivo_id
WHERE dc.ejecutivo IS NOT NULL
ORDER BY dc.ejecutivo;
```

### **PostgreSQL Config**
```yaml
# clients/telefonica-peru/api-config.yaml
database:
  type: "postgresql"
  postgresql:
    host: "telefonica-datamart.postgres"
    port: 5432
    database: "telefonica_datamart"
    schema: "dwh"
    username: "telefonica_api_user"
    password_env: "TELEFONICA_PG_PASSWORD"
    pool_size:
      min: 5
      max: 20
    query_timeout: 30

cache:
  type: "redis"
  redis:
    host: "telefonica-cache.redis"
    port: 6379
    database: 1
    ttl_seconds: 300  # 5 minutos
    key_prefix: "telefonica:api:"

graphql:
  introspection: false  # Producción
  max_query_depth: 10
  max_query_complexity: 1000
```

### **Schema Config Dynamic**
```yaml
# clients/telefonica-peru/graphql-schema.yaml
types:
  GestionData:
    base_fields:
      fecha: "DateTime!"
      ejecutivo: "String"
      servicio: "String!"
      cartera: "String!"
    dynamic_metrics:
      tasa_contactabilidad:
        type: "Float"
        source: "ROUND(contactos_efectivos::float / total_gestiones * 100, 2)"
      pdps_por_hora:
        type: "Float" 
        source: "ROUND(gestiones_pdp::float / horas_trabajadas, 2)"

filters:
  TelefonicaFilters:
    fechaInicio: "DateTime"
    fechaFin: "DateTime"
    ejecutivos: "[String!]"
    servicios: "[String!]"
    carteras: "[String!]"
    zonas: "[String!]"

queries:
  gestiones:
    return_type: "[GestionData!]!"
    filters: "TelefonicaFilters"
    max_results: 10000
    
  availableValues:
    return_type: "DimensionValues!"
    cache_ttl: 600  # 10 minutos
```

### **Load Testing**
```python
# tests/performance/test_api_load.py
import asyncio
import aiohttp
import time

async def test_concurrent_queries():
    """Test 50 consultas simultáneas."""
    
    query = """
    query TelefonicaGestiones($filters: TelefonicaFilters) {
        gestiones(filters: $filters) {
            fecha
            ejecutivo
            servicio
            tasa_contactabilidad
            pdps_por_hora
        }
    }
    """
    
    variables = {
        "filters": {
            "fechaInicio": "2024-01-01",
            "fechaFin": "2024-01-31",
            "servicios": ["MOVIL"]
        }
    }
    
    async def single_request():
        async with aiohttp.ClientSession() as session:
            start = time.time()
            async with session.post(
                "http://localhost:8000/graphql",
                json={"query": query, "variables": variables}
            ) as response:
                result = await response.json()
                end = time.time()
                return end - start, len(result.get("data", {}).get("gestiones", []))
    
    # 50 requests concurrentes
    tasks = [single_request() for _ in range(50)]
    results = await asyncio.gather(*tasks)
    
    times = [r[0] for r in results]
    assert max(times) < 1.0  # Max 1 segundo
    assert sum(times) / len(times) < 0.3  # Promedio <300ms
```

### **Integration Tests**
- [ ] Test conexión PostgreSQL con pool
- [ ] Test cache Redis hit/miss
- [ ] Test schema dinámico generación
- [ ] Test cross-filtering performance
- [ ] Test queries con filtros complejos

## 📁 Estructura de Archivos
```
core-template/src/
├── infrastructure/adapters/postgresql/
│   ├── telefonica_repository.py     # Repository principal
│   ├── connection_pool.py          # Pool de conexiones
│   └── query_builder.py            # Constructor queries optimizadas
├── api/
│   ├── graphql/
│   │   ├── schema_generator.py      # Generator dinámico
│   │   ├── resolvers/              # Resolvers reutilizables
│   │   └── middleware/             # Auth, cache, etc.
│   └── main.py                     # FastAPI app
└── tests/
    ├── integration/
    │   └── test_telefonica_api.py
    └── performance/
        └── test_api_load.py
```

## 🔗 Dependencias
- ETL Pipeline Telefónica (#14)
- PostgreSQL datamart setup (#TBD)
- Redis cache configuration (#TBD)
- GraphQL schema generator (#TBD)

## 📅 Timeline
**Estimación**: 10-14 horas  
**Prioridad**: P1 (Después del ETL)

## 🏷️ Labels
`client-telefonica`, `graphql-api`, `postgresql`, `lean-architecture`, `p1-critical`
