### ISSUE TITLE
[CORE-001] Pipeline ETL básico funcional - Hacer que el proyecto LEVANTE

### ISSUE THREAD

**Issue by reyer3** [reyer3/Pulso-AI#19]
## 🎯 **Objetivo**
Implementar pipeline ETL básico funcional que haga que el proyecto **LEVANTE** con datos reales de Telefónica del Perú.

**Problema actual**: Tenemos configuración perfecta pero `docker-compose up` no funciona porque faltan las implementaciones.

## 📋 **Contexto de Negocio**
- **Cliente**: Telefónica del Perú (configuración completa en Issue #12 ✅)
- **Fuentes**: 8 tablas reales BigQuery identificadas
- **SLA**: Pipeline funcionando en <8 horas desarrollo
- **Objetivo**: `docker-compose up` → Dashboard con datos reales

### Pipeline ETL Básico
- [ ] **BigQueryAdapter** que lea `clients/telefonica-peru/config.yaml`
- [ ] **ETL Service** que procese 1 tabla mínima (ej: `batch_*_master_luna`)
- [ ] **PostgreSQL DWH** con schema dimensional básico
- [ ] **ETL Orchestrator** que ejecute pipeline completo

### API GraphQL Mínima
- [ ] **GraphQL Schema dinámico** basado en config.yaml
- [ ] **1 Query funcional** que retorne datos de PostgreSQL
- [ ] **Resolver básico** para dimensiones y métricas
- [ ] **Connection** PostgreSQL → API

### Frontend Básico
- [ ] **Dashboard mínimo** que muestre datos reales
- [ ] **1 KPI card** (ej: total clientes)
- [ ] **1 tabla simple** (ej: top ejecutivos)
- [ ] **Connection** API → Frontend

### Docker & Infrastructure
- [ ] **docker-compose.yml** que levante todo el stack
- [ ] **PostgreSQL** con inicialización automática
- [ ] **BigQuery credentials** configuradas
- [ ] **Networking** entre servicios funcionando

### **Estructura Target**
```
pulso-ai/
├── docker-compose.yml           # Stack completo
├── services/
│   ├── etl/                     # ETL Service
│   │   ├── Dockerfile
│   │   ├── requirements.txt
│   │   └── src/
│   │       ├── bigquery_adapter.py
│   │       ├── etl_orchestrator.py
│   │       └── postgres_loader.py
│   ├── api/                     # GraphQL API
│   │   ├── Dockerfile
│   │   ├── requirements.txt
│   │   └── src/
│   │       ├── schema_generator.py
│   │       ├── resolvers.py
│   │       └── main.py
│   └── frontend/                # React Dashboard
│       ├── Dockerfile
│       ├── package.json
│       └── src/
│           ├── App.tsx
│           ├── Dashboard.tsx
│           └── api/client.ts
├── infrastructure/
│   ├── postgres/
│   │   ├── init.sql             # Schema inicial
│   │   └── Dockerfile
│   └── secrets/
│       └── bigquery-key.json   # BigQuery credentials
└── clients/telefonica-peru/    # ✅ Ya completado
```

### **ETL Pipeline Mínimo**
```python
# services/etl/src/etl_orchestrator.py
class ETLOrchestrator:
    async def process_telefonica_daily(self, fecha: date):
        """Pipeline mínimo para Telefónica."""
        
        # 1. Extract from BigQuery
        extractor = BigQueryAdapter(self.config.telefonica)
        raw_data = await extractor.extract_master_luna(fecha)
        
        # 2. Transform (mínimo)
        transformer = DataTransformer()
        clean_data = transformer.basic_clean(raw_data)
        
        # 3. Load to PostgreSQL
        loader = PostgreSQLLoader()
        await loader.upsert_dim_cliente(clean_data)
        
        return {"status": "success", "rows": len(clean_data)}
```

### **API GraphQL Mínima**
```python
# services/api/src/schema_generator.py
@strawberry.type
class Cliente:
    cod_luna: int
    nombre: str
    servicio: str

@strawberry.type
class Query:
    @strawberry.field
    async def clientes_telefonica(self) -> List[Cliente]:
        """Query básica que retorna clientes de PostgreSQL."""
        return await ClienteRepository.get_top_100()
```

### **Frontend Mínimo**
```tsx
// services/frontend/src/Dashboard.tsx
export function TelefonicaDashboard() {
  const { data } = useQuery(GET_CLIENTES_TELEFONICA);
  
  return (
    <div className="p-6">
      <KPICard title="Total Clientes" value={data?.clientes?.length} />
      <ClientesTable data={data?.clientes} />
    </div>
  );
}
```

### **BigQuery Connection**
- **Project**: `mibot-222814`
- **Dataset**: `BI_USA`  
- **Tabla inicial**: `batch_P3fV4dWNeMkN5RJMhV8e_master_luna`
- **Credentials**: Service account JSON

### **PostgreSQL Schema**
```sql
-- Mínimo viable
CREATE SCHEMA IF NOT EXISTS telefonica;

CREATE TABLE telefonica.dim_cliente (
    cod_luna INTEGER PRIMARY KEY,
    nombre VARCHAR(255),
    servicio VARCHAR(50),
    created_at TIMESTAMP DEFAULT NOW()
);
```

### **Docker Compose Stack**
```yaml
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pulso_ai
      POSTGRES_USER: pulso_ai
      POSTGRES_PASSWORD: dev_password
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  etl:
    build: ./services/etl
    environment:
      - POSTGRES_URL=postgresql://pulso_ai:dev_password@postgres:5432/pulso_ai
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/bigquery-key.json
    volumes:
      - ./infrastructure/secrets:/secrets
    depends_on:
      - postgres

  api:
    build: ./services/api
    environment:
      - POSTGRES_URL=postgresql://pulso_ai:dev_password@postgres:5432/pulso_ai
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./services/frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/graphql
    ports:
      - "3000:3000"
    depends_on:
      - api
```

### **Test de Pipeline Completo**
```bash
# 1. Levantar stack
docker-compose up -d

# 2. Ejecutar ETL manual
curl -X POST http://localhost:8000/etl/run-telefonica

# 3. Verificar datos en PostgreSQL
docker exec -it postgres psql -U pulso_ai -d pulso_ai -c "SELECT COUNT(*) FROM telefonica.dim_cliente;"

# 4. Query GraphQL
curl -X POST http://localhost:8000/graphql \
  -H "Content-Type: application/json" \
  -d '{"query": "{ clientesTelefonica { codLuna nombre servicio } }"}'

# 5. Verificar Frontend
curl http://localhost:3000
```

## 📊 **Definición de Terminado**

- [ ] ✅ `docker-compose up` levanta sin errores
- [ ] ✅ ETL procesa datos reales de BigQuery
- [ ] ✅ PostgreSQL contiene datos de Telefónica
- [ ] ✅ GraphQL query retorna datos correctos
- [ ] ✅ Frontend muestra dashboard básico
- [ ] ✅ End-to-end funcional en <30 minutos setup
- [ ] ✅ Documentación de setup actualizada

## 🔗 **Dependencias**
- **Issue #12**: ✅ Configuración Telefónica completa
- **BigQuery access**: Credentials válidas requeridas
- **Docker**: Docker y docker-compose instalados

## 📅 **Timeline**
**Estimación**: 6-8 horas  
**Prioridad**: P0 (Blocker crítico - proyecto no levanta sin esto)

## 🚀 **Próximos Pasos Post-Issue**
Una vez completada esta issue:
- **Issue #14**: Ampliar ETL a las 8 tablas completas
- **Issue #15**: Dashboard completo con KPIs multi-canal
- **Issue #16**: Cross-filtering y interactividad

---

## 🎯 **Success Criteria**
**AL FINAL DE ESTA ISSUE**: Un desarrollador nuevo debe poder hacer `git clone` + `docker-compose up` y ver un dashboard funcionando con datos reales de Telefónica del Perú en <30 minutos.

## 🏷️ **Labels**
`core-implementation` `etl-pipeline` `phase-1-mvp` `p0-blocker` `telefonica-peru`
